name: Nations
version: '${project.version}'
main: me.barbosaur.nations.Nations
api-version: 1.19
commands:
  state:
    description: A command
    usage: /<command>
  calibrate:
    description: Калибровать РСЗО
    usage: /<command>
  discord:
    description: Привязать дискорд
    usage: /<command> <link/code>
  cooldown:
    description: Кулдаун
    usage: /<command>
  democraft:
    description: Democraft
    usage: /<command>
depend: [dynmap, AuthMe]
